from __future__ import annotations

import pathlib
import re
import sys


REQUIRED_MARKERS = [
    "IanOS UEFI loader",
    "Mattas kernel entry",
    "Framebuffer base",
    "Framebuffer dimensions",
    "Framebuffer pitch/bpp",
    "User init image base",
    "User init image size",
    "Boot module table",
    "Boot module count",
    "Boot flags",
    "Boot mode normal",
    "Userspace init PID",
    "Userspace process PML4",
    "Userspace owns address space",
    "Userspace init ELF entry",
    "Userspace image pages",
    "Userspace owned pages",
    "Userspace stack top",
    "Userspace main TID",
    "Userspace process mappings PASS",
    "Userspace init marked runnable",
    "Userspace live processes",
    "Userspace active PID",
    "Userspace runnable user threads",
    "Userspace open file descriptors",
    "Userspace argument count",
    "Userspace environment count",
    "Userspace launch context PASS",
    "Userspace ring-3 execution scheduled",
    "Userspace entering ring 3",
    "userland init entered",
    "[shell] boot shell starting",
    "[shell] $ help",
    "[shell] $ echo",
    "[shell] stdout fd online",
    "[shell] $ pid",
    "[shell] pid current",
    "[shell] $ ids",
    "[shell] ids pid",
    "[shell] ids tid",
    "[shell] ids ppid",
    "[shell] ids pgid",
    "[shell] ids kthread",
    "[shell] ids cpu",
    "[shell] $ fgpgid",
    "[shell] fgpgid ",
    "[shell] $ ctx",
    "[shell] ctx pid",
    "[shell] ctx tid",
    "[shell] ctx pstate 0x0000000000000002",
    "[shell] ctx tstate 0x0000000000000003",
    "[shell] ctx rip",
    "[shell] ctx rsp",
    "[shell] ctx cr3",
    "[shell] $ argv",
    "[shell] argv count",
    "[shell] argv init",
    "[shell] $ env",
    "[shell] env count",
    "[shell] env ROOT=/",
    "[shell] env PATH=/bin",
    "[shell] $ export",
    "[shell] export EDITOR=hksh",
    "[shell] export LONGVAR=alpha-beta-gamma-delta-epsilon-zeta-eta-theta-iota-kappa",
    "[shell] env EDITOR=hksh",
    "[shell] env LONGVAR=alpha-beta-gamma-delta-epsilon-zeta-eta-theta-iota-kappa",
    "[shell] env-hksh",
    "[shell] long-alpha-beta-gamma-delta-epsilon-zeta-eta-theta-iota-kappa",
    "[shell] status-1",
    "[shell] path-/bin",
    "[shell] $ which",
    "[shell] which /bin/grep.elf",
    "[shell] $ stat",
    "[shell] stat path /bin/hello.elf",
    "[shell] stat path /etc/os-release",
    "[shell] stat path /etc/hostname",
    "[shell] stat path /tmp",
    "[shell] stat path /dev/null",
    "[shell] stat path /dev/zero",
    "[shell] stat path /dev/tty",
    "[shell] stat path /dev/console",
    "[shell] stat path /proc/meminfo",
    "[shell] stat path /proc/stat",
    "[shell] stat path /proc/block/bootdisk",
    "[shell] stat path /proc/driver/summary",
    "[shell] stat path /proc/driver/devices",
    "[shell] stat path /proc/pci/summary",
    "[shell] stat path /proc/pci/devices",
    "[shell] stat path /proc/irq/summary",
    "[shell] stat path /proc/interrupts",
    "[shell] stat path /proc/tty/summary",
    "[shell] stat path /proc/cpu/summary",
    "[shell] stat path /proc/cpu/topology",
    "[shell] stat path /proc/mounts",
    "[shell] stat path /proc/filesystems",
    "[shell] stat path /proc/fs/vfs",
    "[shell] stat path /proc/cmdline",
    "[shell] stat path /proc/sys/kernel/hostname",
    "[shell] stat path /proc/sys/kernel/ostype",
    "[shell] stat path /proc/sys/kernel/osrelease",
    "[shell] stat path /proc/sys/kernel/version",
    "[shell] stat path /proc/self/status",
    "[shell] stat path /proc/self/fd",
    "[shell] stat path /disk/bootsector.bin",
    "[shell] stat path /mnt/boot/kernel.elf",
    "[shell] stat path /mnt/boot/bin/hello.elf",
    "[shell] stat type memory-file",
    "[shell] stat type directory",
    "[shell] stat type char-device",
    "[shell] stat type virtual-file",
    "[shell] stat size",
    "[shell] stat flags",
    "[shell] $ counts",
    "[shell] counts processes",
    "[shell] counts user threads",
    "[shell] $ fds",
    "[shell] fds pid 0x0000000000000000",
    "[shell] fds fd 0x0000000000000000",
    "[shell] fds fd 0x0000000000000001",
    "[shell] fds fd 0x0000000000000002",
    "[shell] fds path /dev/tty",
    "[shell] fds count 0x0000000000000003",
    "[shell] $ ls",
    "[shell] dir /boot",
    "[shell] dir /user",
    "[shell] dir /bin",
    "[shell] dir /etc",
    "[shell] dir /proc",
    "[shell] dir /dev",
    "[shell] dir /tmp",
    "[shell] dir /disk",
    "[shell] dir /mnt",
    "[shell] file /bin/args.elf",
    "[shell] file /bin/cat.elf",
    "[shell] file /bin/ls.elf",
    "[shell] file /bin/uname.elf",
    "[shell] file /bin/hostname.elf",
    "[shell] file /bin/free.elf",
    "[shell] file /bin/uptime.elf",
    "[shell] file /bin/date.elf",
    "[shell] file /bin/dmesg.elf",
    "[shell] file /bin/ps.elf",
    "[shell] file /bin/pwd.elf",
    "[shell] file /bin/env.elf",
    "[shell] file /bin/sysinfo.elf",
    "[shell] file /bin/fastfetch.elf",
    "[shell] file /bin/sysctl.elf",
    "[shell] file /bin/id.elf",
    "[shell] file /bin/ids.elf",
    "[shell] file /bin/ctx.elf",
    "[shell] file /bin/echo.elf",
    "[shell] file /bin/sleep.elf",
    "[shell] file /bin/true.elf",
    "[shell] file /bin/false.elf",
    "[shell] file /bin/touch.elf",
    "[shell] file /bin/append.elf",
    "[shell] file /bin/rm.elf",
    "[shell] file /bin/cp.elf",
    "[shell] file /bin/mv.elf",
    "[shell] file /bin/wc.elf",
    "[shell] file /bin/grep.elf",
    "[shell] file /bin/tee.elf",
    "[shell] file /bin/mkdir.elf",
    "[shell] file /bin/rmdir.elf",
    "[shell] file /bin/err.elf",
    "[shell] file /bin/stat.elf",
    "[shell] file /bin/whoami.elf",
    "[shell] file /bin/basename.elf",
    "[shell] file /bin/dirname.elf",
    "[shell] file /bin/head.elf",
    "[shell] file /bin/tail.elf",
    "[shell] file /bin/test.elf",
    "[shell] file /bin/sort.elf",
    "[shell] file /bin/uniq.elf",
    "[shell] file /bin/find.elf",
    "[shell] file /bin/hexdump.elf",
    "[shell] file /bin/readelf.elf",
    "[shell] file /bin/sha256sum.elf",
    "[shell] file /bin/cmp.elf",
    "[shell] file /bin/cksum.elf",
    "[shell] file /bin/fold.elf",
    "[shell] file /bin/strings.elf",
    "[shell] file /bin/nl.elf",
    "[shell] file /bin/tr.elf",
    "[shell] file /bin/sed.elf",
    "[shell] file /bin/cut.elf",
    "[shell] file /bin/paste.elf",
    "[shell] file /bin/rev.elf",
    "[shell] file /bin/seq.elf",
    "[shell] file /bin/expr.elf",
    "[shell] file /bin/sh.elf",
    "[shell] file /bin/duptest.elf",
    "[shell] file /bin/fds.elf",
    "[shell] file /bin/lsof.elf",
    "[shell] file /bin/fdinh.elf",
    "[shell] file /bin/ln.elf",
    "[shell] file /bin/readlink.elf",
    "[shell] file /bin/truncate.elf",
    "[shell] file /bin/blk.elf",
    "[shell] file /bin/mount.elf",
    "[shell] file /bin/df.elf",
    "[shell] file /bin/du.elf",
    "[shell] file /bin/lsblk.elf",
    "[shell] file /bin/pipeinfo.elf",
    "[shell] file /bin/kill.elf",
    "[shell] file /bin/killall.elf",
    "[shell] file /bin/pgrep.elf",
    "[shell] file /bin/uyield.elf",
    "[shell] file /bin/ubusy.elf",
    "[shell] file /bin/slowcat.elf",
    "[shell] file /bin/burst.elf",
    "[shell] file /bin/loop.elf",
    "[shell] file /bin/devio.elf",
    "[shell] file /bin/tty.elf",
    "[shell] file /bin/stty.elf",
    "[shell] file /bin/ttyread.elf",
    "[shell] file /bin/clear.elf",
    "[shell] char /dev/null",
    "[shell] char /dev/zero",
    "[shell] char /dev/tty",
    "[shell] char /dev/console",
    "[shell] $ cat",
    "[shell] $ spawn",
    "[shell] spawn pid",
    "[shell] $ usched",
    "[shell] usched current tid",
    "[shell] usched runnable",
    "[shell] usched schedulable",
    "[shell] usched quantum 0x0000000000000004",
    "[shell] usched expired slices",
    "[shell] $ nextuser",
    "[shell] nextuser error 0x0000000000000003",
    "[shell] $ run",
    "[shell] run start pid",
    "[hello] hello from a separate ELF user program",
    "[hello] argc 0x0000000000000003",
    "[hello] argv[0x0000000000000001]=alpha",
    "[hello] argv[0x0000000000000002]=beta",
    "[shell] run exit",
    "[shell] run wait polls 0x0000000000000000",
    "[shell] $ wait",
    "[shell] wait code",
    "[shell] $ reap",
    "[shell] reap pid",
    "[shell] $ jobs",
    "[shell] jobs count 0x0000000000000001",
    "[shell] jobs count 0x0000000000000000",
    "[shell] $ uyielddemo",
    "[shell] uyield child pid",
    "[uyield] child start",
    "Userspace yield switched TID",
    "[shell] uyield parent resumed",
    "[uyield] child resumed",
    "Userspace scheduled after exit PID",
    "[shell] uyield wait code 0x000000000000002a",
    "[shell] uyield reap pid",
    "Userspace preemption gate enable count",
    "Userspace auto preemption enabled",
    "Userspace scheduler preemption gate enabled",
    "[shell] $ upreemptdemo",
    "[shell] upreempt child pid",
    "[ubusy] child start",
    "Userspace APIC preempt switched TID",
    "Userspace APIC preempt switched PID",
    "Userspace preempt switch count",
    "Userspace preemption gate disable count",
    "[ubusy] child done",
    "Userspace scheduler preemption gate disabled",
    "[shell] upreempt wait code 0x0000000000000021",
    "[shell] upreempt reap pid",
    "[shell] $ kill",
    "[shell] kill reason sigkill",
    "state=exited reason=sigkill code=0x0000000000000089",
    "[shell] wait code 0x0000000000000089",
    "[shell] kill reason sigterm",
    "state=exited reason=sigterm code=0x000000000000008f",
    "[shell] wait code 0x000000000000008f",
    "[shell] bg pid",
    "[shell] bg job",
    "[shell] bg scheduled",
    "[loop] start",
    "[shell] $ stop",
    "[shell] stop job ",
    "[shell] stop pgid ",
    "[shell] stop count ",
    "state=stopped",
    "[shell] $ bg",
    "[shell] bg pgid ",
    "[shell] bg continued ",
    "[shell] bg running",
    "job %",
    "cmd=loop",
    "cmd=sleep 5",
    "[shell] $ fg",
    "[shell] fg job",
    "[shell] fg pid",
    "[shell] fgpgid fg ",
    "[shell] fg exit 0x0000000000000005",
    "[shell] reap job pid",
    "[shell] $ wait",
    "[shell] wait mode any-next",
    "Userspace wait-any block count",
    "Userspace wait-any blocked TID",
    "Userspace wait-any switch TID",
    "[sleep] ticks 0x0000000000000005",
    "[shell] wait any pid",
    "[shell] wait any code 0x0000000000000005",
    "[shell] wait any polls",
    "[shell] reap job",
    "[shell] $ hello",
    "[shell] exec pid",
    "[shell] fgpgid exec ",
    "[shell] exec scheduled",
    "Userspace APIC preempt switched TID",
    "Userspace wait block count",
    "Userspace wait blocked TID",
    "Userspace wait target PID",
    "Userspace wait switch TID",
    "[hello] argv[0x0000000000000001]=gamma",
    "[hello] argv[0x0000000000000002]=delta",
    "[shell] exec exit",
    "[shell] exec wait",
    "[shell] exec wait polls 0x0000000000000000",
    "[shell] exec reap",
    "[shell] $ args",
    "[args] argc 0x0000000000000003",
    "[args] argv[0x0000000000000001]=one",
    "[args] argv[0x0000000000000002]=two",
    "[args] argv[0x0000000000000001]=two words",
    "[args] argv[0x0000000000000002]=single quoted",
    "[args] argv[0x0000000000000003]=escaped space",
    "[shell] exec exit 0x0000000000000003",
    "[shell] $ /bin/cat.elf",
    "[cat] path /bin/args.elf",
    "[cat] bytes 0x0000000000000010",
    "[cat] first32 0x00000000464c457f",
    "[shell] exec exit 0x0000000000000010",
    "[shell] $ /bin/ls.elf",
    "[ls] count",
    "[ls] file /bin/cat.elf",
    "[ls] file /bin/ls.elf",
    "[ls] file /bin/uname.elf",
    "[ls] file /bin/hostname.elf",
    "[ls] file /bin/free.elf",
    "[ls] file /bin/uptime.elf",
    "[ls] file /bin/date.elf",
    "[ls] file /bin/dmesg.elf",
    "[ls] file /bin/ps.elf",
    "[ls] file /bin/pwd.elf",
    "[ls] file /bin/env.elf",
    "[ls] file /bin/sysinfo.elf",
    "[ls] file /bin/fastfetch.elf",
    "[ls] file /bin/sysctl.elf",
    "[ls] file /bin/id.elf",
    "[ls] file /bin/echo.elf",
    "[ls] file /bin/sleep.elf",
    "[ls] file /bin/true.elf",
    "[ls] file /bin/false.elf",
    "[ls] file /bin/touch.elf",
    "[ls] file /bin/append.elf",
    "[ls] file /bin/rm.elf",
    "[ls] file /bin/cp.elf",
    "[ls] file /bin/mv.elf",
    "[ls] file /bin/wc.elf",
    "[ls] file /bin/grep.elf",
    "[ls] file /bin/tee.elf",
    "[ls] file /bin/mkdir.elf",
    "[ls] file /bin/rmdir.elf",
    "[ls] file /bin/err.elf",
    "[ls] file /bin/stat.elf",
    "[ls] file /bin/whoami.elf",
    "[ls] file /bin/basename.elf",
    "[ls] file /bin/dirname.elf",
    "[ls] file /bin/head.elf",
    "[ls] file /bin/tail.elf",
    "[ls] file /bin/test.elf",
    "[ls] file /bin/sort.elf",
    "[ls] file /bin/uniq.elf",
    "[ls] file /bin/find.elf",
    "[ls] file /bin/hexdump.elf",
    "[ls] file /bin/readelf.elf",
    "[ls] file /bin/sha256sum.elf",
    "[ls] file /bin/cmp.elf",
    "[ls] file /bin/cksum.elf",
    "[ls] file /bin/fold.elf",
    "[ls] file /bin/strings.elf",
    "[ls] file /bin/nl.elf",
    "[ls] file /bin/tr.elf",
    "[ls] file /bin/sed.elf",
    "[ls] file /bin/cut.elf",
    "[ls] file /bin/paste.elf",
    "[ls] file /bin/rev.elf",
    "[ls] file /bin/seq.elf",
    "[ls] file /bin/expr.elf",
    "[ls] file /bin/sh.elf",
    "[ls] file /bin/duptest.elf",
    "[ls] file /bin/fds.elf",
    "[ls] file /bin/lsof.elf",
    "[ls] file /bin/fdinh.elf",
    "[ls] file /bin/ln.elf",
    "[ls] file /bin/readlink.elf",
    "[ls] file /bin/truncate.elf",
    "[ls] file /bin/blk.elf",
    "[ls] file /bin/mount.elf",
    "[ls] file /bin/df.elf",
    "[ls] file /bin/du.elf",
    "[ls] file /bin/lsblk.elf",
    "[ls] file /bin/pipeinfo.elf",
    "[ls] file /bin/kill.elf",
    "[ls] file /bin/killall.elf",
    "[ls] file /bin/pgrep.elf",
    "[ls] file /bin/ctx.elf",
    "[ls] file /bin/uyield.elf",
    "[ls] file /bin/ubusy.elf",
    "[ls] file /bin/slowcat.elf",
    "[ls] file /bin/burst.elf",
    "[ls] file /bin/loop.elf",
    "[ls] file /bin/devio.elf",
    "[ls] file /bin/tty.elf",
    "[ls] file /bin/stty.elf",
    "[ls] file /bin/ttyread.elf",
    "[ls] file /bin/clear.elf",
    "[ls] file /disk/bootsector.bin",
    "[ls] char /dev/null",
    "[ls] char /dev/zero",
    "[ls] char /dev/tty",
    "[ls] char /dev/console",
    "[ls] dir /proc/self",
    "[ls] virt /proc/meminfo",
    "[ls] virt /proc/uptime",
    "[ls] virt /proc/stat",
    "[ls] virt /proc/interrupts",
    "[ls] dir /proc/block",
    "[ls] dir /proc/driver",
    "[ls] dir /proc/pci",
    "[ls] dir /proc/irq",
    "[ls] dir /proc/tty",
    "[ls] dir /proc/cpu",
    "[ls] virt /proc/processes",
    "[ls] virt /proc/mounts",
    "[ls] virt /proc/filesystems",
    "[ls] virt /proc/cmdline",
    "[ls] dir /proc/fs",
    "[ls] dir /proc/sys",
    "[ls] virt /proc/self/status",
    "[ls] virt /proc/self/fd",
    "[ls] dir /proc/1",
    "[ls] virt /proc/1/status",
    "[ls] dir /proc/1/fd",
    "[ls] dir /proc/sys/kernel",
    "[ls] virt /proc/fs/vfs",
    "[ls] virt /proc/block/bootdisk",
    "[ls] virt /proc/driver/summary",
    "[ls] virt /proc/driver/devices",
    "[ls] virt /proc/pci/summary",
    "[ls] virt /proc/pci/devices",
    "[ls] virt /proc/irq/summary",
    "[ls] virt /proc/tty/summary",
    "[ls] virt /proc/cpu/summary",
    "[ls] virt /proc/cpu/topology",
    "[ls] virt /proc/sys/kernel/hostname",
    "[ls] virt /proc/sys/kernel/ostype",
    "[ls] virt /proc/sys/kernel/osrelease",
    "[ls] virt /proc/sys/kernel/version",
    "[ls] dir /mnt/boot/bin",
    "[ls] file /mnt/boot/kernel.elf",
    "[ls] file /mnt/boot/bin/hello.elf",
    "[ls] file /mnt/boot/user/init.elf",
    "[shell] $ /bin/stat.elf",
    "[stat] path /tmp",
    "[stat] type directory",
    "[stat] flags",
    "[shell] $ whoami",
    "[whoami] root",
    "[shell] $ basename",
    "[basename] init.elf",
    "[shell] $ dirname",
    "[dirname] /user",
    "[shell] $ head",
    "[head] path /etc/os-release",
    "[shell] $ tail",
    "[tail] path /etc/os-release",
    "[shell] $ test",
    "[shell] test-dir-ok",
    "[shell] test-file-ok",
    "[shell] test-missing-ok",
    "[shell] $ /bin/ls.elf",
    "[ls] file /etc/os-release",
    "[ls] file /etc/hostname",
    "[shell] $ /bin/cat.elf",
    "[cat] path /etc/os-release",
    "[cat] text",
    "NAME=IanOS",
    "PRETTY_NAME=\"IanOS 0.1.20\"",
    "[cat] path /etc/hostname",
    "ianos",
    "[cat] path /proc/version",
    "Mattas 0.1.20-stable x86_64 uefi hybrid",
    "[cat] path /proc/meminfo",
    "MemTotal:",
    "PagesFree:",
    "[cat] path /proc/uptime",
    "ticks ",
    "[cat] path /proc/stat",
    "ctxt ",
    "procs_running ",
    "user_pipe_read_blocks ",
    "user_pipe_write_blocks ",
    "user_pipe_read_wakes ",
    "user_pipe_write_wakes ",
    "user_wait_blocks ",
    "user_wait_any_blocks ",
    "user_wait_wakes ",
    "user_sleep_blocks ",
    "user_sleep_wakes ",
    "user_preemption_gate_enables ",
    "user_preemption_gate_disables ",
    "user_preempt_switches ",
    "[cat] path /proc/block/bootdisk",
    "initialized ",
    "sector_size 512",
    "sector_reads ",
    "multi_sector_reads ",
    "cache_hits ",
    "cache_misses ",
    "cache_evictions ",
    "invalid_reads ",
    "null_buffer_rejects ",
    "zero_count_rejects ",
    "oversized_request_rejects ",
    "backend_read_failures ",
    "cache_fills ",
    "cached_entries ",
    "largest_request_sectors ",
    "last_lba ",
    "[cat] path /proc/driver/summary",
    "registered_drivers ",
    "started_drivers ",
    "failed_drivers ",
    "start_attempts ",
    "start_successes ",
    "import_passes ",
    "imported_devices ",
    "ahci_devices ",
    "e1000_devices ",
    "vga_devices ",
    "bus_master_required_devices ",
    "command_bits_union ",
    "[cat] path /proc/driver/devices",
    "DRIVER KIND BDF VENDOR DEVICE REQUIRED_COMMAND_BITS BUS_MASTER STATE",
    "driver ahci kind ahci",
    "driver e1000 kind e1000",
    "driver vga kind vga",
    "state bound",
    "[cat] path /proc/pci/summary",
    "scanned_buses ",
    "devices ",
    "storage_controllers ",
    "network_controllers ",
    "display_controllers ",
    "bridge_devices ",
    "mmio_bars ",
    "driver_candidates ",
    "ahci_candidates ",
    "e1000_candidates ",
    "vga_candidates ",
    "driver_bindings ",
    "ecam_regions ",
    "ecam_verified_devices ",
    "config_probes ",
    "config_probe_failures ",
    "config_ecam_mismatches ",
    "malformed_config_rejects ",
    "preferred_ecam_reads ",
    "legacy_config_reads ",
    "ecam_fallback_reads ",
    "preferred_ecam_writes ",
    "legacy_config_writes ",
    "ecam_write_fallbacks ",
    "command_enable_attempts ",
    "command_enable_successes ",
    "[cat] path /proc/pci/devices",
    "BDF VENDOR DEVICE CLASS SUBCLASS PROGIF COMMAND STATUS DRIVER BARS",
    " driver ahci ",
    " driver e1000 ",
    " driver vga ",
    " bar0 ",
    "[cat] path /proc/irq/summary",
    "pic_remaps ",
    "mask_updates ",
    "legacy_eoi_count ",
    "dispatch_count ",
    "exception_dispatch_count ",
    "irq_dispatch_count ",
    "lapic_dispatch_count ",
    "syscall_dispatch_count ",
    "ioapic_route_prepares ",
    "ioapic_route_match_checks ",
    "ioapic_route_match_successes ",
    "invalid_vectors ",
    "last_vector ",
    "last_irq ",
    "vector_0x20_count ",
    "vector_0x21_count ",
    "vector_0x40_count ",
    "vector_0x41_count ",
    "vector_0x80_count ",
    "lapic_available ",
    "lapic_enabled ",
    "lapic_timer_lvt ",
    "lapic_ticks ",
    "lapic_timer_active ",
    "user_preemption_enabled ",
    "[cat] path /proc/interrupts",
    "VECTOR CPU0 CONTROLLER NAME",
    "32: ",
    "33: ",
    "64: ",
    "65: ",
    "128: ",
    "LAPIC scheduler-timer",
    "LAPIC ipi-work",
    "SYSCALL int80",
    "ERR: ",
    "MIS: ",
    "EOI: ",
    "[cat] path /proc/tty/summary",
    "input_mode ",
    "buffered_input ",
    "write_calls ",
    "bytes_written ",
    "raw_input_bytes ",
    "canonical_input_bytes ",
    "canonical_line_commits ",
    "dropped_input_bytes ",
    "input_high_watermark ",
    "scroll_relative_ops ",
    "scroll_to_bottom_ops ",
    "input_line_resets ",
    "console_visible_columns ",
    "console_visible_rows ",
    "console_cursor_row ",
    "console_viewport_bottom ",
    "console_follow_tail ",
    "console_render_calls ",
    "console_glyph_draws ",
    "console_cells_written ",
    "console_scroll_relative_ops ",
    "console_scroll_to_bottom_ops ",
    "console_input_line_resets ",
    "[cat] path /proc/cpu/summary",
    "cpus ",
    "online ",
    "startup_attempts ",
    "current_cpu ",
    "smp_init_ipi_attempts ",
    "smp_init_ipi_delivered ",
    "smp_startup_ipi_delivered ",
    "smp_ap_checkins ",
    "smp_ipi_work_completed ",
    "smp_queued_work_completed ",
    "smp_tlb_shootdown_completed ",
    "[cat] path /proc/cpu/topology",
    "CPU APIC ACPI ENABLED ONLINE BOOTSTRAP STARTUP STATE DESCRIPTORS LAPIC_TIMER BOOT_WORK IPI_WORK TICKS INTERRUPTS WORK TLB",
    "cpu 0 apic ",
    " enabled 1 ",
    " online 1 ",
    " bootstrap 1 ",
    " state scheduler ",
    " descriptors_ready 1 ",
    " bootstrap_work_done 1 ",
    "cpu 1 apic ",
    " state parked ",
    " ipi_work_done 1 ",
    " tlb_shootdowns ",
    "[cat] path /proc/processes",
    "PID PPID PGID STATE FDS TICKS NAME",
    "state runnable",
    "[cat] path /proc/mounts",
    "boot-modules / vfs rw,mem,writable 0 0",
    "boot-disk0 /mnt/boot fat16 ro,disk 0 0",
    "[cat] path /proc/filesystems",
    "nodev\tproc",
    "fat16",
    "[cat] path /proc/fs/vfs",
    "ram_file_creates ",
    "ram_file_create_rejects ",
    "ram_directory_creates ",
    "ram_directory_create_rejects ",
    "ram_links ",
    "ram_link_rejects ",
    "ram_truncates ",
    "ram_truncate_rejects ",
    "ram_renames ",
    "ram_rename_rejects ",
    "ram_file_deletes ",
    "ram_file_delete_rejects ",
    "ram_directory_deletes ",
    "ram_directory_delete_rejects ",
    "ram_write_bytes ",
    "ram_write_clipped_bytes ",
    "[cat] path /proc/cmdline",
    "BOOT_IMAGE=/boot/kernel.elf",
    "[cat] path /proc/sys/kernel/hostname",
    "ianos",
    "[cat] path /proc/sys/kernel/ostype",
    "IanOS",
    "[cat] path /proc/sys/kernel/osrelease",
    "0.1.20-x86_64",
    "[cat] path /proc/sys/kernel/version",
    "Mattas 0.1.20-stable x86_64 uefi hybrid",
    "[cat] path /proc/self/status",
    "Name:\t/bin/cat.elf",
    "Pid:\t",
    "Threads:\t",
    "[cat] path /proc/self/fd",
    "FD KIND TARGET",
    "fd 0 kind vfs offset 0 path /dev/tty",
    "fd 1 kind vfs offset",
    "fd 2 kind vfs offset 0 path /dev/tty",
    "fd 3 kind vfs",
    "path /proc/self/fd",
    "[cat] path /proc/1/status",
    "Name:\tinit",
    "PGid:\t1",
    "Syscalls:\t",
    "[cat] path /proc/1/fd",
    "fd 0 kind vfs offset 0 path /dev/tty",
    "fd 1 kind vfs offset",
    "fd 2 kind vfs offset 0 path /dev/tty",
    "path /proc/1/fd",
    "[cat] path /tmp/readlink.txt",
    "[readlink] path /proc/self/fd/1",
    "[readlink] target /tmp/readlink.txt",
    "[readlink] bytes 0x0000000000000011",
    "[readlink] numeric /proc/",
    "[readlink] numeric target /tmp/readlink.txt",
    "[readlink] numeric bytes 0x0000000000000011",
    "[readlink] fd entry /proc/",
    "/fd/1",
    "[cat] path /disk/bootsector.bin",
    "[shell] $ /bin/hexdump.elf",
    "[hexdump] path /disk/bootsector.bin",
    "[hexdump] 00000000  eb 3c 90 48 59 42 52 49-44 4f 53 ",
    "[hexdump] bytes 0x0000000000000100",
    "[shell] $ /bin/hexdump.elf",
    "[hexdump] path /etc/os-release",
    "[hexdump] 00000000  4e 41 4d 45 3d 49 61 6e-4f 53 ",
    "[hexdump] bytes ",
    "[shell] $ /bin/readelf.elf",
    "[readelf] path /bin/readelf.elf",
    "[readelf] class ELF64",
    "[readelf] data little-endian",
    "[readelf] type executable",
    "[readelf] machine x86_64",
    "[readelf] entry 0x",
    "[readelf] phnum 0x",
    "[shell] $ /bin/readelf.elf",
    "[readelf] path /mnt/boot/kernel.elf",
    "[readelf] class ELF64",
    "[readelf] machine x86_64",
    "[readelf] shnum 0x",
    "[shell] $ /bin/sha256sum.elf",
    "[sha256sum] e802e368271e45fdf55df4e53791a90976a75c56f22a090d626c2b3f1fe90603  /etc/hostname",
    "[sha256sum] bytes 0x0000000000000006",
    "[shell] $ /bin/sha256sum.elf",
    "[sha256sum] 50997efb5d6db27bded68ec30b27494c8892d0c6d3632d7a8edfd47330570250  /etc/os-release",
    "[sha256sum] bytes 0x000000000000003e",
    "[shell] $ /bin/cksum.elf",
    "[cksum] crc32 0x46de6eca  /etc/hostname",
    "[cksum] bytes 0x0000000000000006",
    "[shell] $ /bin/fold.elf",
    "[fold] path /proc/version",
    "[fold] width 0x000000000000000c",
    "[fold] Mattas 0.1.2",
    "[fold] 0-stable x86",
    "[fold] _64 uefi hyb",
    "[fold] rid",
    "[fold] lines 0x0000000000000004",
    "[fold] bytes 0x0000000000000028",
    "[shell] $ /bin/cmp.elf",
    "[cmp] files /etc/hostname /proc/sys/kernel/hostname",
    "[cmp] equal bytes 0x0000000000000006",
    "[shell] $ /bin/cmp.elf",
    "[cmp] files /etc/hostname /etc/os-release",
    "[cmp] differ byte 0x0000000000000001 left 0x0000000000000069 right 0x000000000000004e",
    "[shell] $ /bin/strings.elf",
    "[strings] path /etc/os-release",
    "[strings] NAME=IanOS",
    "[strings] VERSION=0.1.20",
    "[strings] PRETTY_NAME=\"IanOS 0.1.20\"",
    "[strings] lines 0x0000000000000004",
    "[shell] $ /bin/strings.elf",
    "[strings] path /proc/version",
    "[strings] Mattas 0.1.20-stable x86_64 uefi hybrid",
    "[strings] lines 0x0000000000000001",
    "[shell] $ /bin/nl.elf",
    "[nl] path /etc/os-release",
    "[nl] 1\tNAME=IanOS",
    "[nl] 2\tVERSION=0.1.20",
    "[nl] 3\tID=ianos",
    "[nl] 4\tPRETTY_NAME=\"IanOS 0.1.20\"",
    "[nl] lines 0x0000000000000004",
    "[shell] $ /bin/tr.elf",
    "[tr] path /etc/os-release",
    "[tr] NAME=ianos",
    "[tr] VERsioN=0.1.20",
    "[tr] iD=ianos",
    "[tr] PRETTY_NAME=\"ianos 0.1.20\"",
    "[tr] lines 0x0000000000000004",
    "[tr] bytes 0x000000000000003e",
    "[shell] $ /bin/sed.elf",
    "[sed] path /etc/os-release",
    "[sed] pattern IanOS",
    "[sed] replacement IanOS-dev",
    "[sed] NAME=IanOS-dev",
    "[sed] VERSION=0.1.20",
    "[sed] ID=ianos",
    "[sed] PRETTY_NAME=\"IanOS-dev 0.1.20\"",
    "[sed] lines 0x0000000000000004",
    "[sed] substitutions 0x0000000000000002",
    "[shell] $ /bin/cut.elf",
    "[cut] path /etc/os-release",
    "[cut] delimiter =",
    "[cut] field 0x0000000000000002",
    "[cut] IanOS",
    "[cut] 0.1.20",
    "[cut] ianos",
    "[cut] \"IanOS 0.1.20\"",
    "[cut] lines 0x0000000000000004",
    "[cut] selected 0x0000000000000004",
    "[shell] $ /bin/paste.elf",
    "[paste] left /etc/hostname",
    "[paste] right /proc/sys/kernel/hostname",
    "[paste] ianos\tianos",
    "[paste] lines 0x0000000000000001",
    "[shell] $ /bin/rev.elf",
    "[rev] path /etc/hostname",
    "[rev] sonai",
    "[rev] lines 0x0000000000000001",
    "[rev] bytes 0x0000000000000006",
    "[shell] $ /bin/seq.elf",
    "[seq] 1",
    "[seq] 2",
    "[seq] 3",
    "[seq] count 0x0000000000000003",
    "[shell] $ /bin/expr.elf",
    "[expr] operator +",
    "[expr] result 12",
    "[cat] path /mnt/boot/kernel.elf",
    "[cat] path /mnt/boot/bin/hello.elf",
    "[shell] $ uname",
    "[uname] IanOS 0.1.20-x86_64 x86_64 uefi Mattas 0.1.20-stable",
    "[uname] modules 0x0000000000000057",
    "[shell] $ hostname",
    "[shell] exec exit 0x0000000000000000",
    "[shell] $ free",
    "[free] total pages",
    "[free] free pages",
    "[shell] $ uptime",
    "[uptime] ticks",
    "[shell] $ date",
    "[date] ",
    "[shell] $ dmesg",
    "[dmesg] bytes",
    "[shell] $ /bin/ps.elf",
    "[ps] count",
    "[ps] pid=",
    " pgid=",
    " reason=",
    " syscalls=",
    " last=",
    " ticks=",
    " switches=",
    " preempts=",
    "[ps] threads",
    "[ps] tid=",
    " block=",
    "[shell] $ /bin/pwd.elf",
    "[pwd] /",
    "[shell] $ /bin/env.elf",
    "[env] count",
    "[env] ROOT=/",
    "[env] PATH=/bin",
    "[env] EDITOR=hksh",
    "[env] LONGVAR=alpha-beta-gamma-delta-epsilon-zeta-eta-theta-iota-kappa",
    "[shell] $ unset",
    "[shell] unset EDITOR",
    "[shell] $ sysinfo",
    "[sysinfo] sysname IanOS",
    "[sysinfo] modules 0x0000000000000057",
    "[shell] $ fastfetch",
    "[fastfetch] OS: IanOS 0.1.20-x86_64",
    "[fastfetch] Kernel: Mattas 0.1.20-stable",
    "[fastfetch] Boot: uefi",
    "[shell] $ /bin/sysctl.elf",
    "[sysctl] kernel.hostname = ianos",
    "[sysctl] kernel.ostype = IanOS",
    "[sysctl] kernel.osrelease = 0.1.20-x86_64",
    "[sysctl] kernel.version = Mattas 0.1.20-stable x86_64 uefi hybrid",
    "[shell] $ /bin/sysctl.elf",
    "[sysctl] kernel.osrelease = 0.1.20-x86_64",
    "[shell] $ /bin/id.elf",
    "uid=0(root) gid=0(root) euid=0(root) egid=0(root) pid=",
    "[shell] $ /bin/ids.elf",
    "[ids] pid ",
    "[ids] tid ",
    "[ids] ppid ",
    "[ids] pgid ",
    "[ids] kthread ",
    "[ids] cpu ",
    "[shell] $ /bin/ctx.elf",
    "[ctx] pid ",
    "[ctx] tid ",
    "[ctx] pstate 0x0000000000000002",
    "[ctx] tstate 0x0000000000000003",
    "[ctx] rip ",
    "[ctx] rsp ",
    "[ctx] cr3 ",
    "[shell] $ /bin/devio.elf",
    "[devio] zero bytes 0x0000000000000020",
    "[devio] null bytes ",
    "[devio] char devices ok",
    "[shell] $ /bin/stty.elf",
    "[stty] mode raw",
    "[stty] set canonical",
    "[stty] mode canonical",
    "[stty] set raw",
    "[shell] $ /bin/ttyread.elf",
    "[ttyread] mode canonical",
    "[ttyread] line canonical tty line",
    "[ttyread] bytes 0x0000000000000013",
    "[ttyread] mode raw",
    "[ttyread] canonical stdin ok",
    "[shell] $ /bin/tty.elf",
    "[tty] mode raw",
    "[tty] path /dev/tty",
    "[tty] type char-device",
    "[tty] read idle /dev/tty",
    "[tty] hello tty",
    "[tty] write /dev/tty",
    "[tty] path /dev/console",
    "[tty] read idle /dev/console",
    "[tty] hello console",
    "[tty] write /dev/console",
    "[tty] terminal devices ok",
    "[shell] $ /bin/clear.elf",
    "[shell] exec exit 0x0000000000000000",
    "[shell] $ /bin/blk.elf",
    "[blk] initialized 0x0000000000000001",
    "[blk] sector size 0x0000000000000200",
    "[blk] reads ",
    "[blk] cache hits ",
    "[blk] cache misses ",
    "[blk] lba0 bytes 0x0000000000000200",
    "[blk] lba0 signature 0x000000000000aa55",
    "[blk] oem ",
    "[shell] $ /bin/mount.elf",
    "[mount] count 0x0000000000000002",
    "[mount] boot-modules on / type vfs flags rw,mem",
    "[mount] boot-disk0 on /mnt/boot type fat16 flags ro,disk",
    "[shell] $ /bin/df.elf",
    "[df] filesystems 0x0000000000000002",
    "[df] / vfs boot-modules rw,mem",
    "[df] /mnt/boot fat16 boot-disk0 ro,disk",
    "[df] used bytes ",
    "[shell] $ /bin/du.elf",
    "[du] path /mnt/boot",
    "[du] files ",
    "[du] dirs ",
    "[du] bytes ",
    "[du] disk bytes ",
    "[shell] $ /bin/lsblk.elf",
    "[lsblk] NAME TYPE SIZE SECTORS MOUNTPOINT",
    "[lsblk] bootdisk disk ",
    "[lsblk] initialized 0x0000000000000001",
    "[lsblk] sector size 0x0000000000000200",
    "[lsblk] mount boot-disk0 /mnt/boot fat16 bytes ",
    "[shell] $ /bin/pipeinfo.elf",
    "[pipeinfo] count ",
    "[shell] $ /bin/kill.elf",
    "[kill] target pid",
    "[kill] reason sigterm",
    "[kill] killed 0x0000000000000001",
    "[shell] $ /bin/pgrep.elf",
    "[pgrep] pid ",
    " name /bin/loop.elf",
    "[pgrep] matches 0x0000000000000001",
    "[shell] $ /bin/killall.elf",
    "[killall] match pid ",
    "[killall] name /bin/loop.elf",
    "[killall] reason sigterm",
    "[killall] killed 0x0000000000000001",
    "[shell] $ /bin/echo.elf",
    "external echo works",
    "[shell] $ sleep",
    "[sleep] ticks 0x0000000000000002",
    "Userspace sleep using Local APIC tick",
    "Userspace sleep block count",
    "Userspace sleep blocked TID",
    "Userspace sleep wake tick",
    "Userspace sleep switch TID",
    "Userspace sleep wake count",
    "Userspace Local APIC sleep wakes",
    "[sleep] done",
    "[shell] exec exit 0x0000000000000002",
    "[shell] $ true",
    "[true] ok",
    "[shell] exec exit 0x0000000000000000",
    "[shell] $ false",
    "[false] fail",
    "[shell] exec exit 0x0000000000000001",
    "[shell] $ touch",
    "[touch] created /tmp/note",
    "[shell] $ append",
    "[append] path /tmp/note",
    "[append] bytes 0x0000000000000005",
    "[cat] path /tmp/note",
    "hello",
    "[ls] file /tmp/note",
    "[shell] $ rm",
    "[rm] deleted /tmp/note",
    "[shell] $ sort",
    "[sort] path /tmp/words",
    "[sort] apple",
    "[sort] banana",
    "[sort] carrot",
    "[shell] $ uniq",
    "[uniq] path /tmp/words",
    "[uniq] banana",
    "[uniq] apple",
    "[uniq] carrot",
    "[shell] $ /bin/find.elf",
    "[find] dir /proc/sys",
    "[find] dir /proc/sys/kernel",
    "[find] virt /proc/sys/kernel/osrelease",
    "[find] virt /proc/sys/kernel/version",
    "[shell] $ /bin/find.elf",
    "[find] file /mnt/boot/bin/hello.elf",
    "[find] matches ",
    "[shell] $ /bin/sh.elf",
    "sh-alpha-beta-gamma-delta-epsilon-zeta-eta-theta-iota-kappa",
    "sh-env-/",
    "sh-status-1",
    "sh-redir-ok",
    "[pwd] /",
    "[args] argv[0x0000000000000001]=script words",
    "[args] argv[0x0000000000000002]=plain",
    "[shell] $ sh",
    "[shell] sh script /tmp/script",
    "[shell] cwd /",
    "[whoami] root",
    "[shell] sh lines 0x0000000000000003",
    "[shell] $ /bin/duptest.elf",
    "[duptest] dup fd ",
    "[duptest] dup2 stdout ok",
    "[cat] path /tmp/dup.txt",
    "dup-write",
    "dup2-stdout",
    "[shell] $ /bin/fds.elf",
    "[shell] redirect stdout /tmp/fds.txt",
    "[cat] path /tmp/fds.txt",
    "[fds] fd 0x0000000000000001",
    "[fds] kind vfs",
    "[fds] path /tmp/fds.txt",
    "[shell] pipe stage /bin/echo.elf",
    "[shell] pipe stage /bin/lsof.elf",
    "[shell] pipe stage grep",
    "[lsof] pid ",
    " kind pipe-read ",
    " kind pipe-write ",
    "[shell] $ /bin/fdinh.elf",
    "[fdinh] child code 0x000000000000000e",
    "[fdinh] stdin offset 0x000000000000000e",
    "[fdinh] expected 0x000000000000000e",
    "[cat] path /tmp/fdinherit.out",
    "shared-offset",
    "[shell] $ /bin/ln.elf",
    "[ln] from /tmp/osrel2",
    "[ln] to /tmp/osrel.link",
    "[stat] path /tmp/osrel.link",
    "[stat] links 0x0000000000000002",
    "LINKED",
    "[shell] $ /bin/truncate.elf",
    "[truncate] path /tmp/trunc",
    "[truncate] size 0x0000000000000004",
    "[stat] path /tmp/trunc",
    "[stat] size 0x0000000000000004",
    "abcd[INFO ]",
    "[truncate] size 0x0000000000000008",
    "[stat] size 0x0000000000000008",
    "syscall truncate self-test",
    "syscall rename self-test",
    "[shell] $ cp",
    "[cp] from /etc/os-release",
    "[cp] to /tmp/osrel",
    "[cp] bytes",
    "[cat] path /tmp/osrel",
    "[shell] $ wc",
    "[wc] path /tmp/osrel",
    "[wc] bytes 0x000000000000003e",
    "[wc] lines 0x0000000000000004",
    "[shell] $ mv",
    "[mv] from /tmp/osrel",
    "[mv] to /tmp/osrel2",
    "[mv] mode rename",
    "[cat] path /tmp/osrel2",
    "[shell] $ grep",
    "[grep] VERSION=0.1.20",
    "[grep] matches 0x0000000000000001",
    "[shell] pipe stages 0x0000000000000002",
    "[shell] pipe create ",
    "[shell] pipe stage /bin/cat.elf",
    "[shell] pipe pid ",
    "[shell] pipe pgid ",
    "[shell] pipe group pid ",
    "[shell] pipe job ",
    "[shell] pipe stdout ",
    "[shell] pipe stage grep",
    "[shell] pipe stdin ",
    "[shell] pipe concurrent",
    "[shell] fgpgid pipe ",
    "[grep] path <stdin>",
    "[shell] pipe stage tee",
    "[tee] path /tmp/tee.txt",
    "[tee] bytes ",
    "[cat] path /tmp/tee.txt",
    "[rm] deleted /tmp/tee.txt",
    "[shell] pipe stages 0x0000000000000003",
    "[shell] pipe stage wc",
    "[wc] path <stdin>",
    "[shell] wait job pid ",
    "[shell] wait job code ",
    "[shell] pipe wait polls 0x0000000000000000",
    "[shell] reap job pid ",
    "[shell] pipe complete",
    "[shell] fgpgid shell ",
    "[shell] pipe stage slowcat",
    "Userspace pipe read block count",
    "Userspace pipe read blocked TID",
    "Userspace pipe wake target TID",
    "Userspace pipe read resumed bytes",
    "Userspace pipe read wake count",
    "[slowcat] path /etc/os-release",
    "[shell] pipe stage burst",
    "[burst] bytes 0x0000000000001000",
    "Userspace pipe write block count",
    "Userspace pipe write blocked TID",
    "Userspace pipe write resumed bytes",
    "Userspace pipe write wake count",
    "[tee] path /tmp/big.txt",
    "[tee] bytes 0x0000000000001000",
    "[wc] path /tmp/big.txt",
    "[wc] bytes 0x0000000000001000",
    "[rm] deleted /tmp/big.txt",
    "[shell] pipe stage true",
    "Userspace pipe write broken TID",
    "[burst] write error 0x0000000000000003",
    "[shell] bg pipe pgid ",
    "[shell] bg pipe scheduled",
    "procs=0x0000000000000002",
    "[shell] $ /bin/echo.elf",
    "[shell] redirect stdout /tmp/redirect.txt",
    "[cat] path /tmp/redirect.txt",
    "[shell] redirect stdin /tmp/redirect.txt",
    "[cat] path <stdin>",
    "redirected output",
    "[rm] deleted /tmp/redirect.txt",
    "[shell] redirect stdout /tmp/append.txt",
    "[shell] redirect append stdout /tmp/append.txt",
    "[cat] path /tmp/append.txt",
    "first",
    "second",
    "[rm] deleted /tmp/append.txt",
    "[shell] $ err",
    "[shell] redirect stderr /tmp/stderr.txt",
    "[shell] redirect append stderr /tmp/stderr.txt",
    "[err] stdout online",
    "[cat] path /tmp/stderr.txt",
    "[err] stderr online",
    "[rm] deleted /tmp/stderr.txt",
    "[shell] $ mkdir",
    "[mkdir] created /tmp/work",
    "[shell] cd /tmp/work",
    "[shell] cwd /tmp/work",
    "[touch] created note",
    "[append] path note",
    "nested",
    "[shell] cd /tmp",
    "[rmdir] error",
    "[rm] deleted /tmp/work/note",
    "[rmdir] removed work",
    "[ls] file /tmp/osrel2",
    "[rm] deleted /tmp/osrel2",
    "[shell] $ ps",
    "[shell] threads",
    "[shell] tblock",
    "[shell] $ mem",
    "[shell] $ cpus",
    "[shell] cpus count",
    "[shell] cpu apic",
    "[shell] cpu flags",
    "[shell] $ devices",
    "[shell] $ fb",
    "[shell] $ ticks",
    "[shell] $ history",
    "[shell] history count",
    "[shell] $ echo",
    "[shell] chain-one",
    "[shell] chain-two",
    "[shell] 1",
    "[shell] fallback-ran",
    "[shell] and-ran",
    "[shell] boot shell complete",
    "[shell] interactive shell ready",
    "[shell] interactive prompt enabled",
    "SELFTEST process lifecycle PASS",
    "user thread frame save self-test",
    "SELFTEST launch context PASS",
    "thread-derived process context self-test",
    "SELFTEST file descriptors PASS",
    "IOAPIC redirection entries",
    "Local APIC timer masked config PASS",
    "Local APIC timer countdown PASS",
    "Local APIC timer probe delta",
    "SELFTEST Local APIC timer probe delta",
    "SELFTEST Local APIC timer PASS",
    "CPU topology count",
    "CPU topology online",
    "CPU topology bootstrap",
    "CPU runtime records",
    "CPU runtime current",
    "CPU runtime descriptors ready",
    "CPU runtime LAPIC timer ready",
    "CPU runtime bootstrap work done",
    "CPU runtime IPI work done",
    "CPU runtime parked APIC",
    "SMP startup attempts",
    "SMP INIT IPI delivered count",
    "SMP INIT IPI delivered APIC",
    "SMP SIPI delivered count",
    "SMP SIPI delivered APIC",
    "SMP AP checkins",
    "SMP AP long mode online APIC",
    "SMP AP IPI work complete APIC",
    "SMP AP IPI work completed",
    "SMP AP queued work complete APIC",
    "SMP AP queued work completed",
    "SMP AP TLB shootdown complete APIC",
    "SMP AP TLB shootdown completed",
    "SMP remote TLB shootdowns",
    "SMP online CPUs",
    "MCFG",
    "ECAM region count",
    "ACPI diagnostics RSDP flags",
    "ACPI diagnostics root entries",
    "ACPI diagnostics tables scanned",
    "ACPI diagnostics tables valid",
    "ACPI diagnostics checksum failures=0x0000000000000000",
    "ACPI diagnostics malformed tables=0x0000000000000000",
    "ACPI diagnostics MADT entries",
    "ACPI diagnostics MADT malformed=0x0000000000000000",
    "ACPI diagnostics MADT LAPIC entries",
    "ACPI diagnostics MADT IOAPIC entries",
    "ACPI diagnostics MADT override entries",
    "ACPI diagnostics MCFG entries",
    "ACPI diagnostics ECAM validated",
    "ACPI diagnostics ECAM rejected=0x0000000000000000",
    "ACPI diagnostics ECAM overlaps rejected=0x0000000000000000",
    "IOAPIC IRQ0 masked route prepared",
    "IOAPIC IRQ0 flags",
    "IOAPIC IRQ0 route",
    "PCI scanned buses",
    "PCI total devices",
    "PCI storage controllers",
    "PCI MMIO BARs",
    "PCI command/status",
    "PCI required command bits",
    "PCI driver candidates",
    "PCI ECAM regions",
    "PCI ECAM verified devices",
    "PCI config probes",
    "PCI config probe failures=0x0000000000000000",
    "PCI config ECAM mismatches=0x0000000000000000",
    "PCI malformed config rejects=0x0000000000000004",
    "PCI preferred ECAM reads",
    "PCI legacy config reads=0x0000000000000000",
    "PCI ECAM fallback reads=0x0000000000000000",
    "PCI preferred ECAM writes",
    "PCI legacy config writes=0x0000000000000000",
    "PCI ECAM write fallbacks=0x0000000000000000",
    "PCI selftest preferred ECAM reads",
    "PCI selftest preferred ECAM writes",
    "PCI selftest legacy config writes=0x0000000000000000",
    "PCI selftest command enable attempts=0x0000000000000001",
    "PCI selftest command enable successes=0x0000000000000001",
    "PCI AHCI candidates",
    "PCI e1000 candidates",
    "PCI VGA candidates",
    "PCI driver bindings",
    "PCI AHCI bindings",
    "PCI e1000 bindings",
    "PCI VGA bindings",
    "PCI binding command bits",
    "Driver PCI devices bound",
    "Driver registered count",
    "Driver start attempts",
    "Driver start successes",
    "Driver start failures=0x0000000000000000",
    "Driver import passes",
    "Driver imported devices",
    "Driver skipped bindings=0x0000000000000000",
    "Driver AHCI devices",
    "Driver e1000 devices",
    "Driver VGA devices",
    "Driver bus-master devices",
    "Driver command bits union",
    "Driver PCI device kind",
    "Driver PCI device command bits",
    "Driver started count",
    "Driver failed count",
    "Driver selftest imported devices",
    "Driver selftest bus-master devices",
    "Driver selftest command bits union",
    "SELFTEST driver manager PASS",
    "AHCI controller present",
    "AHCI controller bdf",
    "AHCI ABAR base",
    "AHCI command requirements",
    "AHCI HBA mapped",
    "AHCI CAP",
    "AHCI GHC",
    "AHCI version",
    "AHCI ports implemented",
    "AHCI implemented port count",
    "AHCI active port count",
    "AHCI identify attempted",
    "AHCI identify success",
    "AHCI identify word0",
    "AHCI identify capabilities",
    "AHCI read lba0 attempted",
    "AHCI read lba0 success",
    "AHCI read lba0 boot signature",
    "AHCI read lba0 fstype",
    "Block boot disk initialized",
    "SELFTEST block cache PASS",
    "Block cache reads",
    "Block cache multi reads",
    "Block cache hits",
    "Block cache misses",
    "Block cache evictions",
    "Block cache invalid reads",
    "Block cache null rejects=0x0000000000000002",
    "Block cache zero rejects=0x0000000000000001",
    "Block cache oversized rejects=0x0000000000000001",
    "Block cache backend failures=0x0000000000000000",
    "Block cache fills",
    "Block cache cached entries",
    "Block cache largest request",
    "Block cache last LBA",
    "FAT16 disk mount /mnt/boot",
    "FAT16 mounted entries",
    "SELFTEST AHCI PASS",
    "e1000 adapter present",
    "e1000 adapter bdf",
    "e1000 MMIO base",
    "e1000 MMIO mapped=0x0000000000000001",
    "e1000 register reads",
    "e1000 CTRL",
    "e1000 STATUS",
    "e1000 link up=0x0000000000000001",
    "e1000 full duplex=0x0000000000000001",
    "e1000 link speed Mbps=0x00000000000003e8",
    "e1000 PCI bus speed MHz",
    "e1000 PCI bus width bits",
    "e1000 EECD",
    "e1000 interrupts masked=0x0000000000000001",
    "e1000 interrupts acked=0x0000000000000001",
    "e1000 MAC address",
    "e1000 command requirements",
    "e1000 command enabled=0x0000000000000001",
    "e1000 register writes",
    "e1000 rings allocated=0x0000000000000001",
    "e1000 rings programmed=0x0000000000000001",
    "e1000 RX desc count=0x0000000000000010",
    "e1000 TX desc count=0x0000000000000008",
    "e1000 RX buffer count=0x0000000000000010",
    "e1000 TX buffer count=0x0000000000000008",
    "e1000 TX next index=0x0000000000000001",
    "e1000 TX last index=0x0000000000000000",
    "e1000 TX reclaim checks=0x0000000000000001",
    "e1000 TX busy failures=0x0000000000000000",
    "e1000 TX null rejects=0x0000000000000001",
    "e1000 TX length rejects=0x0000000000000002",
    "e1000 TX validation smoke attempted=0x0000000000000001",
    "e1000 TX validation smoke passed=0x0000000000000001",
    "e1000 RCTL",
    "e1000 TCTL",
    "e1000 RDBA",
    "e1000 RDLEN=0x0000000000000100",
    "e1000 TDBA",
    "e1000 TDLEN=0x0000000000000080",
    "e1000 ring registers verified=0x0000000000000001",
    "e1000 RDH/RDT",
    "e1000 TDH/TDT",
    "e1000 TX smoke attempted=0x0000000000000001",
    "e1000 TX smoke completed=0x0000000000000001",
    "e1000 TX smoke length=0x000000000000003c",
    "e1000 TX packets submitted=0x0000000000000001",
    "e1000 TX packets completed=0x0000000000000001",
    "e1000 RX idle polled=0x0000000000000001",
    "e1000 RX ring idle=0x0000000000000001",
    "e1000 RX ready descriptors=0x0000000000000000",
    "e1000 RX first status=0x0000000000000000",
    "e1000 RX poll calls=0x0000000000000001",
    "e1000 RX empty polls=0x0000000000000001",
    "e1000 RX packets received=0x0000000000000000",
    "e1000 RX bytes received=0x0000000000000000",
    "e1000 RX small buffer drops=0x0000000000000000",
    "e1000 RX poll smoke attempted=0x0000000000000001",
    "e1000 RX poll smoke empty=0x0000000000000001",
    "SELFTEST e1000 PASS",
    "VGA adapter present",
    "VGA adapter bdf",
    "VGA MMIO base",
    "VGA command requirements",
    "SELFTEST VGA PASS",
    "Device inventory count",
    "Device inventory storage",
    "Device inventory network",
    "Device inventory display",
    "Device inventory resources",
    "Device inventory resource count",
    "Device info class",
    "Device info first resource",
    "Device info storage resource",
    "Device info network resource",
    "Device info display resource",
    "SELFTEST device inventory PASS",
    "SELFTEST console begin",
    "Console visible columns",
    "Console visible rows",
    "Console cursor row",
    "Console render calls",
    "Console glyph draws",
    "Console scroll ops",
    "Console input line resets",
    "Console viewport self-test",
    "SELFTEST console PASS",
    "SELFTEST terminal begin",
    "Terminal canonical input self-test",
    "Terminal raw input self-test",
    "Terminal raw overflow self-test",
    "Terminal dropped input bytes",
    "Terminal input high watermark=0x0000000000000100",
    "Terminal scroll relative ops",
    "Terminal scroll bottom ops",
    "Terminal input line resets",
    "SELFTEST terminal PASS",
    "PS/2 keyboard initialized",
    "VFS node count",
    "VFS memory files",
    "VFS memory bytes",
    "VFS open handles",
    "VFS character device self-test",
    "VFS proc virtual file self-test",
    "VFS directory entry self-test",
    "VFS normalized path self-test",
    "VFS RAM file creates",
    "VFS RAM file create rejects",
    "VFS RAM directory creates",
    "VFS RAM directory create rejects",
    "VFS RAM links",
    "VFS RAM link rejects",
    "VFS RAM truncates",
    "VFS RAM truncate rejects",
    "VFS RAM renames",
    "VFS RAM rename rejects",
    "VFS RAM file deletes",
    "VFS RAM file delete rejects",
    "VFS RAM directory deletes",
    "VFS RAM directory delete rejects",
    "VFS RAM write bytes",
    "VFS RAM clipped write bytes",
    "SELFTEST VFS PASS",
    "SELFTEST PCI PASS",
    "SELFTEST PMM PASS",
    "PMM alloc page calls",
    "PMM alloc contiguous calls",
    "PMM failed allocations",
    "PMM invalid frees",
    "PMM peak used pages",
    "SELFTEST VMM PASS",
    "VMM mapped pages",
    "VMM unmapped pages",
    "VMM failed maps",
    "VMM duplicate rejects",
    "VMM unaligned rejects",
    "VMM absent unmap rejects",
    "VMM remote shootdowns",
    "GDT/TSS loaded",
    "SELFTEST overall PASS",
    "SELFTEST address-space PASS",
    "SELFTEST IRQ0 GSI",
    "SELFTEST IRQ1 GSI",
    "IRQ PIC remaps",
    "IRQ mask updates",
    "IRQ route prepares",
    "IRQ route match checks",
    "IRQ route match successes",
    "SELFTEST IRQ routing PASS",
    "SELFTEST syscall PASS",
    "syscall fd self-test",
    "fd dup info self-test",
    "fd inheritance self-test",
    "user thread reap self-test",
    "path normalization self-test",
    "syscall seek self-test",
    "syscall device inventory self-test",
    "syscall framebuffer self-test",
    "syscall memory stats self-test",
    "syscall block device self-test",
    "VFS mount table self-test",
    "syscall mount table self-test",
    "syscall system info self-test",
    "syscall kernel log self-test",
    "syscall accounting self-test",
    "syscall process info self-test",
    "syscall launch context self-test",
    "syscall scheduler stats self-test",
    "syscall CPU topology self-test",
    "syscall datetime self-test",
    "syscall current ids self-test",
    "syscall pipe info self-test",
    "syscall process group self-test",
    "syscall foreground process group self-test",
    "syscall stop continue process group self-test",
    "syscall vfs node self-test",
    "syscall readdir self-test",
    "syscall cwd self-test",
    "syscall directory self-test",
    "syscall link self-test",
    "syscall relative fd self-test",
    "syscall spawn self-test",
    "syscall quoted argv self-test",
    "syscall kill reason self-test",
    "syscall sigterm reason self-test",
    "syscall user scheduler self-test",
    "syscall user context self-test",
    "syscall user preemption gate self-test",
    "syscall wait reap self-test",
    "syscall argument self-test",
    "syscall environment self-test",
    "syscall read-key self-test",
    "syscall stdio fd self-test",
    "[selftest] stdout fd write syscall",
    "syscall write self-test",
    "[selftest] terminal write syscall",
    "syscall terminal control self-test",
    "syscall retired run-process self-test",
    "syscall vfs self-test",
    "syscall debug-log self-test",
    "cooperative yield PASS",
    "Local APIC scheduler timer enabled",
    "preempt demo thread A start",
    "preempt demo thread B start",
    "sleep demo thread sleeping",
    "sleep demo thread woke",
    "preempt demo both reached target",
    "Local APIC scheduler timer stopped",
    "Local APIC timer ticks",
    "Local APIC sleep delta",
    "IRQ dispatch count",
    "IRQ LAPIC dispatch count",
    "IRQ vector 0x40 count",
    "IRQ legacy EOI count",
    "IRQ invalid vectors=0x0000000000000000",
    "Local APIC timer preemption PASS",
    "Kernel initialization complete",
]

FORBIDDEN_MARKERS = [
    "[ERROR] exception vector=",
    "preemptive two-thread demo FAIL",
    "scheduler sleep/wake demo FAIL",
    "Local APIC timer preemption FAIL",
    "kernel timer preemption deferred",
    "SELFTEST overall FAIL",
    "should-not-run",
]

ALTERNATIVE_MARKERS = [
    ("Userspace pipe read eof TID", "Userspace pipe write broken TID"),
]

REQUIRED_PATTERNS = [
    r"\[shell\] usched expired slices 0x(?!0000000000000000)[0-9a-fA-F]{16}",
]


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: validate_boot_log.py <qemu-serial.log>", file=sys.stderr)
        return 2
    path = pathlib.Path(sys.argv[1])
    if not path.exists():
        print(f"boot log missing: {path}", file=sys.stderr)
        return 1
    text = path.read_text(encoding="utf-8", errors="replace")
    marker_text = re.sub(r"\[INFO \][^\n]*\n", "", text)
    ok = True
    for marker in REQUIRED_MARKERS:
        if marker not in text and marker not in marker_text:
            print(f"MISSING {marker}", file=sys.stderr)
            ok = False
    for markers in ALTERNATIVE_MARKERS:
        if not any(marker in text or marker in marker_text for marker in markers):
            print(f"MISSING one of {', '.join(markers)}", file=sys.stderr)
            ok = False
    for pattern in REQUIRED_PATTERNS:
        if not re.search(pattern, text) and not re.search(pattern, marker_text):
            print(f"MISSING pattern {pattern}", file=sys.stderr)
            ok = False
    for marker in FORBIDDEN_MARKERS:
        if marker in text:
            print(f"FORBIDDEN {marker}", file=sys.stderr)
            ok = False
    if ok:
        print("boot log validation passed")
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
